#!/bin/bash

# usage
# branch (string || branch)

# example
# branch fix-things

if git show-ref refs/heads/$1 --quiet; then
  git add --all
  git stash
  git checkout $1
  git stash pop
else
  master
  deps-install
  git checkout -b $1
fi
