#!/bin/bash

# setup
# install https://hub.github.com

# usage
# pull-request (hub args)

# example
# pull-request -l 'merge okay' -o

# get current branch
CURRENT_BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)

# maintain arg quotes - https://stackoverflow.com/a/24179878/537998
function requote() {
  local res=""
  for x in "${@}" ; do
    # try to figure out if quoting was required for the $x:
    grep -q "[[:space:]]" <<< "$x" && res="${res} '${x}'" || res="${res} ${x}"
  done
  # remove first space and print:
  sed -e 's/^ //' <<< "${res}"
}
CMD=$(requote "${@}")

rebase &&
push-force &&
eval hub pull-request ${CMD}
