#!/bin/bash
#
# use like this
# rebase

CURRENT_BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD) && \
git checkout master && \
git pull && \
git checkout $CURRENT_BRANCH && \
git rebase master
