#!/bin/bash

# get current branch
CURRENT_BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)

git add --all
git stash
master-no-stash
git checkout $CURRENT_BRANCH
git rebase master
git stash pop
