#!/bin/bash

# get current branch
CURRENT_BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)

if [ $1 ]; then
  git checkout $1 &&
  rebase &&
  push-force &&
  git checkout $CURRENT_BRANCH
else
  rebase &&
  push-force
fi






