#!/bin/bash
#
# use like this
# rebase-and-push

# get current branch
CURRENT_BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD) && \

rebase &&
git push --force --set-upstream origin $CURRENT_BRANCH
