#!/bin/bash
#
# use like this
# rebase

# get current branch
CURRENT_BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD) && \

master && \
git checkout $CURRENT_BRANCH && \
git rebase master
